apiVersion: v1
kind: Service
metadata:
  name: dvdrental-service
  namespace: k8test
spec:
  selector:
    app: dvdrental-deployment
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30009
  type: NodePort
