apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvdrental-deployment
  namespace: k8test
  labels:
    app: dvdrental-deployment
spec:
  replicas: 2
  template:
    metadata:
      name: dvdrental-deployment
      labels:
        app: dvdrental-deployment
    spec:
      containers:
        - name: dvdrental-deployment
          image: cretaralviiier/dvdrental
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
      restartPolicy: Always
  selector:
    matchLabels:
      app: dvdrental
