spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dvdrental-service-database:5432/dvdrental
    username: dvdrentaluser
    password: dvdrentalpassword
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true
  application:
    name:
server:
  port: 8087
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
